"use client";
import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// Translations
const translations = {
  en: {
    // Navbar
    nav: {
      home: 'Home',
      about: 'About',
      features: 'Features',
      support: 'Support',
      dashboard: 'Dashboard',
      myTracks: 'My Tracks',
      history: 'History',
      myProfile: 'My Profile',
      login: 'Login',
      getStarted: 'Get Started',
      logout: 'Logout',
      settings: 'Settings',
    },
    // Home Page
    home: {
      heroTitle1: 'Split Your Music',
      heroTitle2: 'Royalties Fairly',
      heroDesc: 'The modern Web3 platform for creators. Upload tracks, assign ownership percentages, and automate payouts with transparent blockchain technology.',
      howItWorks: 'How It Works',
      whyHarmoniq: 'Why',
      fairSplits: 'Fair Splits',
      fairSplitsDesc: 'Every collaborator gets their exact share. No middlemen, no delays, no disputes.',
      blockchainPowered: 'Blockchain Powered',
      blockchainPoweredDesc: 'Smart contracts ensure transparency. Once splits are set, they are immutable and trustless.',
      powerfulFeatures: 'Powerful Features',
      everythingYouNeed: 'Everything you need to manage your music business.',
      trackUpload: 'Track Upload',
      trackUploadDesc: 'Upload your masters directly. We support high-quality WAV and FLAC formats.',
      smartSplits: 'Smart Splits',
      smartSplitsDesc: 'Define percentages for every contributor. 20% to the drummer? Done in one click.',
      secure: 'Secure',
      secureDesc: 'Your data is encrypted and ownership records are immutable.',
      autoPayouts: 'Auto Payouts',
      autoPayoutsDesc: 'When earnings hit the account, they are automatically routed to your wallet.',
      footer: '© 2025 Harmoniq. All rights reserved.',
    },
    // About Page
    about: {
      title: 'About',
      subtitle: 'Reimagining the music industry through blockchain transparency and fairness.',
      ourMission: 'Our Mission',
      ourMissionDesc: 'To eliminate the confusion in music royalties. We believe every producer, songwriter, and vocalist deserves to be paid exactly what they are owed, instantly.',
      theSpeed: 'The Speed',
      theSpeedDesc: 'Traditional royalties take 3-6 months. Harmoniq takes 3-6 seconds using smart contracts and Web3 technology.',
      theCommunity: 'The Community',
      theCommunityDesc: 'Built by musicians, for musicians. We understand the struggle of tracking split sheets and chasing payments.',
      whoWeAre: 'Who We Are',
      whoWeAreDesc1: 'Harmoniq was created by artists who experienced firsthand the challenges of royalty distribution. Traditional systems are slow, opaque, and often unfair to creators.',
      whoWeAreDesc2: 'We leverage blockchain technology to create immutable ownership records, instant payment distribution, and complete transparency. Once a split is agreed upon, it cannot be altered without consensus from all parties.',
      whoWeAreDesc3: 'Our platform empowers artists to focus on what they do best—creating music—while we handle the complex backend of royalty management with precision and fairness.',
    },
    // Features Page
    features: {
      title: 'Platform',
      titleHighlight: 'Features',
      subtitle: 'Everything you need to manage your music royalties with complete transparency.',
      trackUpload: 'Track Upload',
      trackUploadDesc: 'Upload your masters directly. We support high-quality WAV and FLAC formats.',
      ownershipSplits: 'Ownership Splits',
      ownershipSplitsDesc: 'Define percentages for every contributor. Set splits that are immutable and transparent.',
      realTimeTracking: 'Real-Time Royalty Tracking',
      realTimeTrackingDesc: 'See earnings as they happen. Live feed from Spotify, Apple Music, and more.',
      blockchainSecurity: 'Blockchain Security',
      blockchainSecurityDesc: 'Your data is encrypted and ownership records are immutable on the blockchain.',
      fraudDetection: 'Fraud Detection',
      fraudDetectionDesc: 'Automated systems detect unusual activity and protect your earnings.',
      automatedPayouts: 'Automated Payouts',
      automatedPayoutsDesc: "When earnings hit your account, they're automatically routed to your wallet.",
      teamCollaboration: 'Team Collaboration',
      teamCollaborationDesc: 'Invite collaborators and manage splits with full transparency and consensus.',
      nftReady: 'NFT Ready',
      nftReadyDesc: 'Mint tracks as NFTs and unlock new revenue streams for your music.',
    },
    // Support Page
    support: {
      title: 'Support',
      titleHighlight: 'Center',
      subtitle: 'Get help with your account, payments, and more.',
      contactUs: 'Contact Us',
      contactDesc: 'Having trouble with your wallet or uploads? Send us a message.',
      yourEmail: 'Your Email',
      describeIssue: 'Describe your issue...',
      sendMessage: 'Send Message',
      quickHelp: 'Quick Help',
      emailSupport: 'Email Support',
      documentation: 'Documentation',
      documentationDesc: 'Learn how to use the platform step-by-step',
      communityDiscord: 'Community Discord',
      communityDiscordDesc: 'Join our Discord for real-time support',
      faq: 'Frequently Asked Questions',
      faq1q: 'How do royalty splits work?',
      faq1a: 'When you upload a track, you define ownership percentages for each collaborator. These splits are locked into a smart contract and cannot be changed without consensus from all parties.',
      faq2q: 'How long do payouts take?',
      faq2a: 'Payouts are instant once earnings are received. Traditional royalty systems take 3-6 months, but Harmoniq distributes payments within seconds using blockchain technology.',
      faq3q: 'What wallets are supported?',
      faq3a: 'We currently support Ethereum wallets like MetaMask, WalletConnect, and Coinbase Wallet. More chains and wallets will be added soon.',
      faq4q: 'Is my data secure?',
      faq4a: 'Yes! All ownership records are stored on the blockchain, making them immutable and transparent. Your personal data is encrypted and we never share it with third parties.',
      faq5q: 'Can I change splits after uploading?',
      faq5a: 'No. Once a split is registered on the blockchain, it cannot be altered. This ensures fairness and prevents disputes. Always double-check before submitting.',
    },
    // Login Page
    login: {
      welcomeBack: 'Welcome Back',
      accessDashboard: 'Access your Artist Dashboard',
      email: 'Email',
      password: 'Password',
      logIn: 'Log In',
      noAccount: "Don't have an account?",
      signUp: 'Sign Up',
      allFieldsRequired: 'All fields are required',
      welcomeBackToast: 'Welcome back!',
    },
    // Register Page
    register: {
      joinHarmoniq: 'Join Harmoniq',
      createIdentity: 'Create your Artist Identity',
      artistName: 'Artist Name',
      artistNamePlaceholder: 'Ex. The Weeknd',
      email: 'Email',
      password: 'Password',
      initializeDashboard: 'Initialize Dashboard',
      alreadyHaveAccount: 'Already have an account?',
      logIn: 'Log In',
      allFieldsRequired: 'All fields are required',
      passwordTooShort: 'Password must be at least 6 characters',
      accountCreated: 'Account created successfully!',
    },
    // Dashboard Page
    dashboard: {
      title: 'Dashboard',
      overview: 'Overview of your smart contract performance.',
      mainnetConnected: 'MAINNET CONNECTED',
      totalBalance: 'Total Balance',
      totalStreams: 'Total Streams',
      activeTracks: 'Active Tracks',
      collaborators: 'Collaborators',
      thisMonth: 'this month',
      keepGrowing: 'Keep growing!',
      uploadToStart: 'Upload tracks to start',
      tracksEarning: 'Tracks earning',
      noTracksUploaded: 'No tracks uploaded',
      activeSplits: 'Active splits',
      noActiveSplits: 'No active splits',
      noEarningsYet: 'No earnings yet',
      liveStream: 'Live Stream',
      realTimeEvents: 'Real-time usage events',
      noActivityYet: 'No activity yet',
      uploadTracksToSee: 'Upload tracks to see live streams',
      viewAllHistory: 'View All History',
    },
    // Tracks Page
    tracks: {
      title: 'My Tracks',
      uploadNew: 'Upload New',
      cancel: 'Cancel',
      trackMetadata: '1. Track Metadata',
      trackTitle: 'Track Title',
      genre: 'Genre (e.g. Synthwave)',
      ownershipSplits: '2. Ownership Splits',
      addPerson: 'Add Person',
      walletName: 'Wallet / Name',
      totalAllocation: 'Total Allocation:',
      mintNft: 'Mint NFT & Register Splits',
      noTracksYet: 'No Tracks Yet',
      uploadFirstTrack: 'Upload your first track to start earning royalties',
      uploadYourFirst: 'Upload Your First Track',
      master: 'Master',
      live: 'Live',
      titleRequired: 'Title is required',
      splitsMustEqual: 'Splits must equal 100%. Current:',
      trackMinted: 'Track minted successfully!',
      smartContractDeployed: 'Smart contract deployed!',
      trackDeleted: 'Track deleted',
    },
    // History Page
    history: {
      title: 'Royalty History',
      searchPlaceholder: 'Search by track name or platform (e.g., Spotify)...',
      noTransactionHistory: 'No Transaction History',
      paymentsWillAppear: 'Your royalty payments will appear here once you start earning',
      noTransactionsFound: 'No transactions found matching',
      paid: 'Paid',
      pending: 'Pending',
    },
    // Profile Page
    profile: {
      wallet: 'Wallet',
      availableBalance: 'Available Balance',
      withdraw: 'Withdraw',
      processing: 'Processing...',
      accountDetails: 'Account Details',
      edit: 'Edit',
      cancel: 'Cancel',
      displayName: 'Display Name',
      email: 'Email',
      saveChanges: 'Save Changes',
      payoutMethod: 'Payout Method',
      ethereumMainnet: 'Ethereum Mainnet',
      connected: 'Connected',
      change: 'Change',
      dangerZone: 'Danger Zone',
      dangerWarning: 'Once you delete your account, there is no going back. Please be certain.',
      signOut: 'Sign Out',
      profileUpdated: 'Profile updated successfully!',
      nameEmpty: 'Name cannot be empty',
      emailEmpty: 'Email cannot be empty',
      invalidEmail: 'Please enter a valid email',
      noFunds: 'No funds to withdraw',
      initiatingTransfer: 'Initiating Blockchain Transfer...',
      transferred: 'ETH transferred to wallet!',
      transactionHash: 'Transaction Hash',
      profilePictureUpdated: 'Profile picture updated!',
      profilePictureRemoved: 'Profile picture removed',
      selectImage: 'Please select an image file',
      imageTooLarge: 'Image must be less than 5MB',
      uploadFailed: 'Failed to upload image',
      removePhoto: 'Remove photo',
    },
    // Settings Page
    settings: {
      title: 'Settings',
      subtitle: 'Manage your account preferences and privacy settings',
      notifications: 'Notifications',
      emailNotifications: 'Email Notifications',
      emailNotificationsDesc: 'Receive updates via email',
      pushNotifications: 'Push Notifications',
      pushNotificationsDesc: 'Browser push notifications',
      royaltyAlerts: 'Royalty Alerts',
      royaltyAlertsDesc: 'Get notified when royalties are received',
      privacySecurity: 'Privacy & Security',
      profileVisibility: 'Profile Visibility',
      public: 'Public',
      private: 'Private',
      showBalance: 'Show Balance',
      showBalanceDesc: 'Display balance on profile',
      twoFactorAuth: 'Two-Factor Authentication',
      twoFactorAuthDesc: 'Add an extra layer of security',
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm New Password',
      updatePassword: 'Update Password',
      enterCurrentPassword: 'Enter current password',
      enterNewPassword: 'Enter new password',
      confirmNewPassword: 'Confirm new password',
      audio: 'Audio',
      soundEffects: 'Sound Effects',
      soundEffectsDesc: 'Enable interface sounds',
      volume: 'Volume',
      language: 'Language',
      selectLanguage: 'Select Language',
      notificationsEnabled: 'Notifications enabled',
      notificationsDisabled: 'Notifications disabled',
      privacyUpdated: 'Privacy settings updated',
      soundEnabled: 'Sound effects enabled',
      soundDisabled: 'Sound effects disabled',
      fillAllFields: 'Please fill all password fields',
      passwordsNoMatch: 'New passwords do not match',
      passwordTooShort: 'Password must be at least 8 characters',
      passwordUpdated: 'Password updated successfully',
      loginRequired: 'Please log in to access settings',
    },
    // Common
    common: {
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      save: 'Save',
      delete: 'Delete',
      confirm: 'Confirm',
      back: 'Back',
    },
  },
  ru: {
    // Navbar
    nav: {
      home: 'Главная',
      about: 'О нас',
      features: 'Возможности',
      support: 'Поддержка',
      dashboard: 'Панель',
      myTracks: 'Мои треки',
      history: 'История',
      myProfile: 'Мой профиль',
      login: 'Войти',
      getStarted: 'Начать',
      logout: 'Выйти',
      settings: 'Настройки',
    },
    // Home Page
    home: {
      heroTitle1: 'Разделяйте музыкальные',
      heroTitle2: 'Роялти справедливо',
      heroDesc: 'Современная Web3 платформа для создателей. Загружайте треки, назначайте проценты владения и автоматизируйте выплаты с прозрачной блокчейн-технологией.',
      howItWorks: 'Как это работает',
      whyHarmoniq: 'Почему',
      fairSplits: 'Честное разделение',
      fairSplitsDesc: 'Каждый соавтор получает свою точную долю. Без посредников, без задержек, без споров.',
      blockchainPowered: 'На блокчейне',
      blockchainPoweredDesc: 'Смарт-контракты обеспечивают прозрачность. После установки доли неизменны и не требуют доверия.',
      powerfulFeatures: 'Мощные функции',
      everythingYouNeed: 'Всё, что нужно для управления музыкальным бизнесом.',
      trackUpload: 'Загрузка треков',
      trackUploadDesc: 'Загружайте мастер-треки напрямую. Поддерживаем WAV и FLAC форматы.',
      smartSplits: 'Умные доли',
      smartSplitsDesc: 'Определяйте проценты для каждого участника. 20% барабанщику? Один клик.',
      secure: 'Безопасно',
      secureDesc: 'Ваши данные зашифрованы, записи о владении неизменны.',
      autoPayouts: 'Авто-выплаты',
      autoPayoutsDesc: 'При поступлении средств они автоматически направляются на ваш кошелёк.',
      footer: '© 2025 Harmoniq. Все права защищены.',
    },
    // About Page
    about: {
      title: 'О',
      subtitle: 'Переосмысление музыкальной индустрии через прозрачность и справедливость блокчейна.',
      ourMission: 'Наша миссия',
      ourMissionDesc: 'Устранить путаницу в музыкальных роялти. Мы верим, что каждый продюсер, автор и вокалист заслуживает получить именно то, что ему причитается, мгновенно.',
      theSpeed: 'Скорость',
      theSpeedDesc: 'Традиционные роялти занимают 3-6 месяцев. Harmoniq — 3-6 секунд благодаря смарт-контрактам и Web3 технологиям.',
      theCommunity: 'Сообщество',
      theCommunityDesc: 'Создано музыкантами для музыкантов. Мы понимаем сложности отслеживания долей и погони за платежами.',
      whoWeAre: 'Кто мы',
      whoWeAreDesc1: 'Harmoniq создан артистами, которые на собственном опыте столкнулись с проблемами распределения роялти. Традиционные системы медленные, непрозрачные и часто несправедливы к создателям.',
      whoWeAreDesc2: 'Мы используем блокчейн-технологию для создания неизменных записей о владении, мгновенного распределения платежей и полной прозрачности. После согласования доля не может быть изменена без согласия всех сторон.',
      whoWeAreDesc3: 'Наша платформа позволяет артистам сосредоточиться на том, что они делают лучше всего — создании музыки — пока мы занимаемся сложным управлением роялти с точностью и справедливостью.',
    },
    // Features Page
    features: {
      title: 'Возможности',
      titleHighlight: 'платформы',
      subtitle: 'Всё необходимое для управления музыкальными роялти с полной прозрачностью.',
      trackUpload: 'Загрузка треков',
      trackUploadDesc: 'Загружайте мастер-треки напрямую. Поддерживаем WAV и FLAC форматы.',
      ownershipSplits: 'Разделение владения',
      ownershipSplitsDesc: 'Определяйте проценты для каждого участника. Устанавливайте неизменные и прозрачные доли.',
      realTimeTracking: 'Отслеживание в реальном времени',
      realTimeTrackingDesc: 'Смотрите доходы по мере поступления. Прямая трансляция из Spotify, Apple Music и других.',
      blockchainSecurity: 'Безопасность блокчейна',
      blockchainSecurityDesc: 'Ваши данные зашифрованы, записи о владении неизменны в блокчейне.',
      fraudDetection: 'Обнаружение мошенничества',
      fraudDetectionDesc: 'Автоматические системы обнаруживают необычную активность и защищают ваши доходы.',
      automatedPayouts: 'Автоматические выплаты',
      automatedPayoutsDesc: 'При поступлении средств они автоматически направляются на ваш кошелёк.',
      teamCollaboration: 'Командная работа',
      teamCollaborationDesc: 'Приглашайте соавторов и управляйте долями с полной прозрачностью и консенсусом.',
      nftReady: 'Готово для NFT',
      nftReadyDesc: 'Минтите треки как NFT и открывайте новые источники дохода для вашей музыки.',
    },
    // Support Page
    support: {
      title: 'Центр',
      titleHighlight: 'поддержки',
      subtitle: 'Получите помощь с аккаунтом, платежами и другими вопросами.',
      contactUs: 'Связаться с нами',
      contactDesc: 'Проблемы с кошельком или загрузками? Отправьте нам сообщение.',
      yourEmail: 'Ваш Email',
      describeIssue: 'Опишите вашу проблему...',
      sendMessage: 'Отправить',
      quickHelp: 'Быстрая помощь',
      emailSupport: 'Email поддержка',
      documentation: 'Документация',
      documentationDesc: 'Узнайте, как использовать платформу пошагово',
      communityDiscord: 'Сообщество Discord',
      communityDiscordDesc: 'Присоединяйтесь к нашему Discord для поддержки в реальном времени',
      faq: 'Часто задаваемые вопросы',
      faq1q: 'Как работает разделение роялти?',
      faq1a: 'При загрузке трека вы определяете проценты владения для каждого соавтора. Эти доли фиксируются в смарт-контракте и не могут быть изменены без согласия всех сторон.',
      faq2q: 'Как долго занимают выплаты?',
      faq2a: 'Выплаты мгновенны после получения доходов. Традиционные системы роялти занимают 3-6 месяцев, но Harmoniq распределяет платежи за секунды благодаря блокчейн-технологии.',
      faq3q: 'Какие кошельки поддерживаются?',
      faq3a: 'Сейчас мы поддерживаем Ethereum кошельки: MetaMask, WalletConnect и Coinbase Wallet. Скоро добавим больше сетей и кошельков.',
      faq4q: 'Мои данные в безопасности?',
      faq4a: 'Да! Все записи о владении хранятся в блокчейне, что делает их неизменными и прозрачными. Ваши личные данные зашифрованы и никогда не передаются третьим лицам.',
      faq5q: 'Можно ли изменить доли после загрузки?',
      faq5a: 'Нет. После регистрации в блокчейне доля не может быть изменена. Это обеспечивает справедливость и предотвращает споры. Всегда проверяйте перед отправкой.',
    },
    // Login Page
    login: {
      welcomeBack: 'С возвращением',
      accessDashboard: 'Войдите в панель артиста',
      email: 'Email',
      password: 'Пароль',
      logIn: 'Войти',
      noAccount: 'Нет аккаунта?',
      signUp: 'Регистрация',
      allFieldsRequired: 'Все поля обязательны',
      welcomeBackToast: 'С возвращением!',
    },
    // Register Page
    register: {
      joinHarmoniq: 'Присоединяйтесь к Harmoniq',
      createIdentity: 'Создайте свой профиль артиста',
      artistName: 'Имя артиста',
      artistNamePlaceholder: 'Напр. The Weeknd',
      email: 'Email',
      password: 'Пароль',
      initializeDashboard: 'Создать панель',
      alreadyHaveAccount: 'Уже есть аккаунт?',
      logIn: 'Войти',
      allFieldsRequired: 'Все поля обязательны',
      passwordTooShort: 'Пароль должен быть не менее 6 символов',
      accountCreated: 'Аккаунт успешно создан!',
    },
    // Dashboard Page
    dashboard: {
      title: 'Панель',
      overview: 'Обзор производительности ваших смарт-контрактов.',
      mainnetConnected: 'MAINNET ПОДКЛЮЧЕН',
      totalBalance: 'Общий баланс',
      totalStreams: 'Всего прослушиваний',
      activeTracks: 'Активные треки',
      collaborators: 'Соавторы',
      thisMonth: 'в этом месяце',
      keepGrowing: 'Продолжайте расти!',
      uploadToStart: 'Загрузите треки для начала',
      tracksEarning: 'Треки приносят доход',
      noTracksUploaded: 'Нет загруженных треков',
      activeSplits: 'Активные доли',
      noActiveSplits: 'Нет активных долей',
      noEarningsYet: 'Пока нет доходов',
      liveStream: 'Прямая трансляция',
      realTimeEvents: 'События в реальном времени',
      noActivityYet: 'Пока нет активности',
      uploadTracksToSee: 'Загрузите треки для просмотра прямой трансляции',
      viewAllHistory: 'Посмотреть всю историю',
    },
    // Tracks Page
    tracks: {
      title: 'Мои треки',
      uploadNew: 'Загрузить',
      cancel: 'Отмена',
      trackMetadata: '1. Метаданные трека',
      trackTitle: 'Название трека',
      genre: 'Жанр (напр. Synthwave)',
      ownershipSplits: '2. Разделение владения',
      addPerson: 'Добавить',
      walletName: 'Кошелёк / Имя',
      totalAllocation: 'Общее распределение:',
      mintNft: 'Создать NFT и зарегистрировать доли',
      noTracksYet: 'Пока нет треков',
      uploadFirstTrack: 'Загрузите первый трек, чтобы начать получать роялти',
      uploadYourFirst: 'Загрузить первый трек',
      master: 'Мастер',
      live: 'Активен',
      titleRequired: 'Требуется название',
      splitsMustEqual: 'Сумма долей должна равняться 100%. Текущая:',
      trackMinted: 'Трек успешно создан!',
      smartContractDeployed: 'Смарт-контракт развёрнут!',
      trackDeleted: 'Трек удалён',
    },
    // History Page
    history: {
      title: 'История роялти',
      searchPlaceholder: 'Поиск по названию трека или платформе (напр. Spotify)...',
      noTransactionHistory: 'Нет истории транзакций',
      paymentsWillAppear: 'Ваши выплаты роялти появятся здесь, когда вы начнёте зарабатывать',
      noTransactionsFound: 'Не найдено транзакций по запросу',
      paid: 'Выплачено',
      pending: 'В ожидании',
    },
    // Profile Page
    profile: {
      wallet: 'Кошелёк',
      availableBalance: 'Доступный баланс',
      withdraw: 'Вывести',
      processing: 'Обработка...',
      accountDetails: 'Данные аккаунта',
      edit: 'Изменить',
      cancel: 'Отмена',
      displayName: 'Отображаемое имя',
      email: 'Эл. почта',
      saveChanges: 'Сохранить',
      payoutMethod: 'Способ выплаты',
      ethereumMainnet: 'Ethereum Mainnet',
      connected: 'Подключено',
      change: 'Изменить',
      dangerZone: 'Опасная зона',
      dangerWarning: 'После удаления аккаунта восстановить его будет невозможно. Будьте уверены.',
      signOut: 'Выйти',
      profileUpdated: 'Профиль успешно обновлён!',
      nameEmpty: 'Имя не может быть пустым',
      emailEmpty: 'Email не может быть пустым',
      invalidEmail: 'Введите корректный email',
      noFunds: 'Нет средств для вывода',
      initiatingTransfer: 'Инициализация блокчейн-перевода...',
      transferred: 'ETH переведено на кошелёк!',
      transactionHash: 'Хэш транзакции',
      profilePictureUpdated: 'Фото профиля обновлено!',
      profilePictureRemoved: 'Фото профиля удалено',
      selectImage: 'Выберите изображение',
      imageTooLarge: 'Изображение должно быть менее 5МБ',
      uploadFailed: 'Не удалось загрузить изображение',
      removePhoto: 'Удалить фото',
    },
    // Settings Page
    settings: {
      title: 'Настройки',
      subtitle: 'Управляйте настройками аккаунта и конфиденциальности',
      notifications: 'Уведомления',
      emailNotifications: 'Email уведомления',
      emailNotificationsDesc: 'Получать обновления по email',
      pushNotifications: 'Push-уведомления',
      pushNotificationsDesc: 'Уведомления в браузере',
      royaltyAlerts: 'Оповещения о роялти',
      royaltyAlertsDesc: 'Уведомления о получении роялти',
      privacySecurity: 'Конфиденциальность',
      profileVisibility: 'Видимость профиля',
      public: 'Публичный',
      private: 'Приватный',
      showBalance: 'Показывать баланс',
      showBalanceDesc: 'Отображать баланс в профиле',
      twoFactorAuth: 'Двухфакторная аутентификация',
      twoFactorAuthDesc: 'Дополнительный уровень защиты',
      changePassword: 'Изменить пароль',
      currentPassword: 'Текущий пароль',
      newPassword: 'Новый пароль',
      confirmPassword: 'Подтвердите пароль',
      updatePassword: 'Обновить пароль',
      enterCurrentPassword: 'Введите текущий пароль',
      enterNewPassword: 'Введите новый пароль',
      confirmNewPassword: 'Подтвердите новый пароль',
      audio: 'Звук',
      soundEffects: 'Звуковые эффекты',
      soundEffectsDesc: 'Включить звуки интерфейса',
      volume: 'Громкость',
      language: 'Язык',
      selectLanguage: 'Выберите язык',
      notificationsEnabled: 'Уведомления включены',
      notificationsDisabled: 'Уведомления отключены',
      privacyUpdated: 'Настройки приватности обновлены',
      soundEnabled: 'Звуковые эффекты включены',
      soundDisabled: 'Звуковые эффекты отключены',
      fillAllFields: 'Заполните все поля пароля',
      passwordsNoMatch: 'Пароли не совпадают',
      passwordTooShort: 'Пароль должен быть не менее 8 символов',
      passwordUpdated: 'Пароль успешно обновлён',
      loginRequired: 'Войдите для доступа к настройкам',
    },
    // Common
    common: {
      loading: 'Загрузка...',
      error: 'Ошибка',
      success: 'Успешно',
      save: 'Сохранить',
      delete: 'Удалить',
      confirm: 'Подтвердить',
      back: 'Назад',
    },
  },
  fr: {
    // Navbar
    nav: {
      home: 'Accueil',
      about: 'À propos',
      features: 'Fonctionnalités',
      support: 'Support',
      dashboard: 'Tableau de bord',
      myTracks: 'Mes morceaux',
      history: 'Historique',
      myProfile: 'Mon profil',
      login: 'Connexion',
      getStarted: 'Commencer',
      logout: 'Déconnexion',
      settings: 'Paramètres',
    },
    // Home Page
    home: {
      heroTitle1: 'Partagez vos',
      heroTitle2: 'Redevances équitablement',
      heroDesc: 'La plateforme Web3 moderne pour les créateurs. Téléchargez des morceaux, attribuez des pourcentages de propriété et automatisez les paiements avec une technologie blockchain transparente.',
      howItWorks: 'Comment ça marche',
      whyHarmoniq: 'Pourquoi',
      fairSplits: 'Partages équitables',
      fairSplitsDesc: 'Chaque collaborateur reçoit sa part exacte. Pas d\'intermédiaires, pas de retards, pas de litiges.',
      blockchainPowered: 'Propulsé par la blockchain',
      blockchainPoweredDesc: 'Les contrats intelligents garantissent la transparence. Une fois les parts définies, elles sont immuables.',
      powerfulFeatures: 'Fonctionnalités puissantes',
      everythingYouNeed: 'Tout ce dont vous avez besoin pour gérer votre activité musicale.',
      trackUpload: 'Téléchargement de morceaux',
      trackUploadDesc: 'Téléchargez vos masters directement. Nous supportons les formats WAV et FLAC haute qualité.',
      smartSplits: 'Partages intelligents',
      smartSplitsDesc: 'Définissez les pourcentages pour chaque contributeur. 20% au batteur ? Un seul clic.',
      secure: 'Sécurisé',
      secureDesc: 'Vos données sont chiffrées et les enregistrements de propriété sont immuables.',
      autoPayouts: 'Paiements automatiques',
      autoPayoutsDesc: 'Quand les revenus arrivent, ils sont automatiquement envoyés vers votre portefeuille.',
      footer: '© 2025 Harmoniq. Tous droits réservés.',
    },
    // About Page
    about: {
      title: 'À propos de',
      subtitle: 'Réinventer l\'industrie musicale grâce à la transparence et l\'équité de la blockchain.',
      ourMission: 'Notre mission',
      ourMissionDesc: 'Éliminer la confusion dans les redevances musicales. Nous croyons que chaque producteur, auteur-compositeur et chanteur mérite d\'être payé exactement ce qui lui est dû, instantanément.',
      theSpeed: 'La rapidité',
      theSpeedDesc: 'Les redevances traditionnelles prennent 3-6 mois. Harmoniq prend 3-6 secondes grâce aux contrats intelligents et à la technologie Web3.',
      theCommunity: 'La communauté',
      theCommunityDesc: 'Créé par des musiciens, pour des musiciens. Nous comprenons la difficulté de suivre les feuilles de partage et de poursuivre les paiements.',
      whoWeAre: 'Qui nous sommes',
      whoWeAreDesc1: 'Harmoniq a été créé par des artistes qui ont vécu les défis de la distribution des redevances. Les systèmes traditionnels sont lents, opaques et souvent injustes envers les créateurs.',
      whoWeAreDesc2: 'Nous utilisons la technologie blockchain pour créer des enregistrements de propriété immuables, une distribution instantanée des paiements et une transparence totale. Une fois qu\'un partage est convenu, il ne peut être modifié sans le consensus de toutes les parties.',
      whoWeAreDesc3: 'Notre plateforme permet aux artistes de se concentrer sur ce qu\'ils font le mieux — créer de la musique — pendant que nous gérons la complexité des redevances avec précision et équité.',
    },
    // Features Page
    features: {
      title: 'Fonctionnalités de la',
      titleHighlight: 'plateforme',
      subtitle: 'Tout ce dont vous avez besoin pour gérer vos redevances musicales en toute transparence.',
      trackUpload: 'Téléchargement de morceaux',
      trackUploadDesc: 'Téléchargez vos masters directement. Nous supportons les formats WAV et FLAC.',
      ownershipSplits: 'Partages de propriété',
      ownershipSplitsDesc: 'Définissez les pourcentages pour chaque contributeur. Des partages immuables et transparents.',
      realTimeTracking: 'Suivi en temps réel',
      realTimeTrackingDesc: 'Voyez vos revenus en direct. Flux en direct de Spotify, Apple Music, et plus.',
      blockchainSecurity: 'Sécurité blockchain',
      blockchainSecurityDesc: 'Vos données sont chiffrées et les enregistrements de propriété sont immuables sur la blockchain.',
      fraudDetection: 'Détection de fraude',
      fraudDetectionDesc: 'Des systèmes automatisés détectent les activités inhabituelles et protègent vos revenus.',
      automatedPayouts: 'Paiements automatisés',
      automatedPayoutsDesc: 'Quand les revenus arrivent, ils sont automatiquement envoyés vers votre portefeuille.',
      teamCollaboration: 'Collaboration d\'équipe',
      teamCollaborationDesc: 'Invitez des collaborateurs et gérez les partages en toute transparence et consensus.',
      nftReady: 'Prêt pour les NFT',
      nftReadyDesc: 'Créez des NFT de vos morceaux et débloquez de nouvelles sources de revenus.',
    },
    // Support Page
    support: {
      title: 'Centre de',
      titleHighlight: 'support',
      subtitle: 'Obtenez de l\'aide pour votre compte, vos paiements et plus encore.',
      contactUs: 'Nous contacter',
      contactDesc: 'Des problèmes avec votre portefeuille ou vos téléchargements ? Envoyez-nous un message.',
      yourEmail: 'Votre e-mail',
      describeIssue: 'Décrivez votre problème...',
      sendMessage: 'Envoyer',
      quickHelp: 'Aide rapide',
      emailSupport: 'Support par e-mail',
      documentation: 'Documentation',
      documentationDesc: 'Apprenez à utiliser la plateforme étape par étape',
      communityDiscord: 'Communauté Discord',
      communityDiscordDesc: 'Rejoignez notre Discord pour un support en temps réel',
      faq: 'Questions fréquentes',
      faq1q: 'Comment fonctionnent les partages de redevances ?',
      faq1a: 'Lors du téléchargement d\'un morceau, vous définissez les pourcentages de propriété pour chaque collaborateur. Ces partages sont verrouillés dans un contrat intelligent et ne peuvent être modifiés sans le consensus de toutes les parties.',
      faq2q: 'Combien de temps prennent les paiements ?',
      faq2a: 'Les paiements sont instantanés une fois les revenus reçus. Les systèmes traditionnels prennent 3-6 mois, mais Harmoniq distribue les paiements en quelques secondes grâce à la blockchain.',
      faq3q: 'Quels portefeuilles sont supportés ?',
      faq3a: 'Nous supportons actuellement les portefeuilles Ethereum comme MetaMask, WalletConnect et Coinbase Wallet. Plus de chaînes et de portefeuilles seront ajoutés bientôt.',
      faq4q: 'Mes données sont-elles sécurisées ?',
      faq4a: 'Oui ! Tous les enregistrements de propriété sont stockés sur la blockchain, les rendant immuables et transparents. Vos données personnelles sont chiffrées et jamais partagées avec des tiers.',
      faq5q: 'Puis-je modifier les partages après le téléchargement ?',
      faq5a: 'Non. Une fois qu\'un partage est enregistré sur la blockchain, il ne peut être modifié. Cela garantit l\'équité et prévient les litiges. Vérifiez toujours avant de soumettre.',
    },
    // Login Page
    login: {
      welcomeBack: 'Bon retour',
      accessDashboard: 'Accédez à votre tableau de bord artiste',
      email: 'E-mail',
      password: 'Mot de passe',
      logIn: 'Connexion',
      noAccount: 'Pas de compte ?',
      signUp: 'S\'inscrire',
      allFieldsRequired: 'Tous les champs sont requis',
      welcomeBackToast: 'Bon retour !',
    },
    // Register Page
    register: {
      joinHarmoniq: 'Rejoignez Harmoniq',
      createIdentity: 'Créez votre identité d\'artiste',
      artistName: 'Nom d\'artiste',
      artistNamePlaceholder: 'Ex. The Weeknd',
      email: 'E-mail',
      password: 'Mot de passe',
      initializeDashboard: 'Initialiser le tableau de bord',
      alreadyHaveAccount: 'Vous avez déjà un compte ?',
      logIn: 'Connexion',
      allFieldsRequired: 'Tous les champs sont requis',
      passwordTooShort: 'Le mot de passe doit comporter au moins 6 caractères',
      accountCreated: 'Compte créé avec succès !',
    },
    // Dashboard Page
    dashboard: {
      title: 'Tableau de bord',
      overview: 'Aperçu des performances de vos contrats intelligents.',
      mainnetConnected: 'MAINNET CONNECTÉ',
      totalBalance: 'Solde total',
      totalStreams: 'Écoutes totales',
      activeTracks: 'Morceaux actifs',
      collaborators: 'Collaborateurs',
      thisMonth: 'ce mois',
      keepGrowing: 'Continuez à grandir !',
      uploadToStart: 'Téléchargez des morceaux pour commencer',
      tracksEarning: 'Morceaux qui rapportent',
      noTracksUploaded: 'Aucun morceau téléchargé',
      activeSplits: 'Partages actifs',
      noActiveSplits: 'Aucun partage actif',
      noEarningsYet: 'Pas encore de revenus',
      liveStream: 'Flux en direct',
      realTimeEvents: 'Événements en temps réel',
      noActivityYet: 'Pas encore d\'activité',
      uploadTracksToSee: 'Téléchargez des morceaux pour voir le flux en direct',
      viewAllHistory: 'Voir tout l\'historique',
    },
    // Tracks Page
    tracks: {
      title: 'Mes morceaux',
      uploadNew: 'Télécharger',
      cancel: 'Annuler',
      trackMetadata: '1. Métadonnées du morceau',
      trackTitle: 'Titre du morceau',
      genre: 'Genre (ex. Synthwave)',
      ownershipSplits: '2. Partages de propriété',
      addPerson: 'Ajouter',
      walletName: 'Portefeuille / Nom',
      totalAllocation: 'Allocation totale :',
      mintNft: 'Créer NFT et enregistrer les partages',
      noTracksYet: 'Pas encore de morceaux',
      uploadFirstTrack: 'Téléchargez votre premier morceau pour commencer à gagner des redevances',
      uploadYourFirst: 'Télécharger votre premier morceau',
      master: 'Master',
      live: 'Actif',
      titleRequired: 'Le titre est requis',
      splitsMustEqual: 'Les partages doivent égaler 100%. Actuel :',
      trackMinted: 'Morceau créé avec succès !',
      smartContractDeployed: 'Contrat intelligent déployé !',
      trackDeleted: 'Morceau supprimé',
    },
    // History Page
    history: {
      title: 'Historique des redevances',
      searchPlaceholder: 'Rechercher par nom de morceau ou plateforme (ex. Spotify)...',
      noTransactionHistory: 'Aucun historique de transactions',
      paymentsWillAppear: 'Vos paiements de redevances apparaîtront ici une fois que vous commencerez à gagner',
      noTransactionsFound: 'Aucune transaction trouvée pour',
      paid: 'Payé',
      pending: 'En attente',
    },
    // Profile Page
    profile: {
      wallet: 'Portefeuille',
      availableBalance: 'Solde disponible',
      withdraw: 'Retirer',
      processing: 'Traitement...',
      accountDetails: 'Détails du compte',
      edit: 'Modifier',
      cancel: 'Annuler',
      displayName: 'Nom affiché',
      email: 'E-mail',
      saveChanges: 'Enregistrer',
      payoutMethod: 'Mode de paiement',
      ethereumMainnet: 'Ethereum Mainnet',
      connected: 'Connecté',
      change: 'Changer',
      dangerZone: 'Zone de danger',
      dangerWarning: 'Une fois votre compte supprimé, il n\'y a pas de retour en arrière. Soyez certain.',
      signOut: 'Se déconnecter',
      profileUpdated: 'Profil mis à jour avec succès !',
      nameEmpty: 'Le nom ne peut pas être vide',
      emailEmpty: 'L\'email ne peut pas être vide',
      invalidEmail: 'Veuillez entrer un email valide',
      noFunds: 'Aucun fonds à retirer',
      initiatingTransfer: 'Initialisation du transfert blockchain...',
      transferred: 'ETH transféré au portefeuille !',
      transactionHash: 'Hash de transaction',
      profilePictureUpdated: 'Photo de profil mise à jour !',
      profilePictureRemoved: 'Photo de profil supprimée',
      selectImage: 'Veuillez sélectionner une image',
      imageTooLarge: 'L\'image doit faire moins de 5 Mo',
      uploadFailed: 'Échec du téléchargement de l\'image',
      removePhoto: 'Supprimer la photo',
    },
    // Settings Page
    settings: {
      title: 'Paramètres',
      subtitle: 'Gérez vos préférences de compte et paramètres de confidentialité',
      notifications: 'Notifications',
      emailNotifications: 'Notifications par e-mail',
      emailNotificationsDesc: 'Recevoir des mises à jour par e-mail',
      pushNotifications: 'Notifications push',
      pushNotificationsDesc: 'Notifications du navigateur',
      royaltyAlerts: 'Alertes de redevances',
      royaltyAlertsDesc: 'Être notifié lors de la réception de redevances',
      privacySecurity: 'Confidentialité et sécurité',
      profileVisibility: 'Visibilité du profil',
      public: 'Public',
      private: 'Privé',
      showBalance: 'Afficher le solde',
      showBalanceDesc: 'Afficher le solde sur le profil',
      twoFactorAuth: 'Authentification à deux facteurs',
      twoFactorAuthDesc: 'Ajouter une couche de sécurité supplémentaire',
      changePassword: 'Changer le mot de passe',
      currentPassword: 'Mot de passe actuel',
      newPassword: 'Nouveau mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      updatePassword: 'Mettre à jour le mot de passe',
      enterCurrentPassword: 'Entrez le mot de passe actuel',
      enterNewPassword: 'Entrez le nouveau mot de passe',
      confirmNewPassword: 'Confirmez le nouveau mot de passe',
      audio: 'Audio',
      soundEffects: 'Effets sonores',
      soundEffectsDesc: 'Activer les sons de l\'interface',
      volume: 'Volume',
      language: 'Langue',
      selectLanguage: 'Sélectionner la langue',
      notificationsEnabled: 'Notifications activées',
      notificationsDisabled: 'Notifications désactivées',
      privacyUpdated: 'Paramètres de confidentialité mis à jour',
      soundEnabled: 'Effets sonores activés',
      soundDisabled: 'Effets sonores désactivés',
      fillAllFields: 'Veuillez remplir tous les champs de mot de passe',
      passwordsNoMatch: 'Les mots de passe ne correspondent pas',
      passwordTooShort: 'Le mot de passe doit comporter au moins 8 caractères',
      passwordUpdated: 'Mot de passe mis à jour avec succès',
      loginRequired: 'Veuillez vous connecter pour accéder aux paramètres',
    },
    // Common
    common: {
      loading: 'Chargement...',
      error: 'Erreur',
      success: 'Succès',
      save: 'Enregistrer',
      delete: 'Supprimer',
      confirm: 'Confirmer',
      back: 'Retour',
    },
  },
};

const languages = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
];

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  // Load saved language on mount
  useEffect(() => {
    const savedLang = localStorage.getItem('harmoniq_language');
    if (savedLang && translations[savedLang]) {
      setLanguage(savedLang);
    }
  }, []);

  // Change language
  const changeLanguage = (langCode) => {
    if (translations[langCode]) {
      setLanguage(langCode);
      localStorage.setItem('harmoniq_language', langCode);
    }
  };

  // Get translation helper
  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
